[package]
name = "week10-project"
version = "0.1.0"
authors = ["SLMT <sam123456777@gmail.com>"]

[dependencies]
piston_window = "0.123.0"
rand = "0.8"
clap = { version = "4.1.4", features = ["derive"] }
