[package]
name = "week11-proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = {version="4.0.32", features=["derive"]}
qrcode = "0.12.0"
image = "0.23.14"