[package]
name = "jz368_week4_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly ={ version = "0.8.3", features = ["kaleido"]}
clap = { version = "4.1.4", features = ["derive"] }